(cl:defpackage laser_assembler-srv
  (:use )
  (:export
   "ASSEMBLESCANS"
   "<ASSEMBLESCANS-REQUEST>"
   "ASSEMBLESCANS-REQUEST"
   "<ASSEMBLESCANS-RESPONSE>"
   "ASSEMBLESCANS-RESPONSE"
   "ASSEMBLESCANS2"
   "<ASSEMBLESCANS2-REQUEST>"
   "ASSEMBLESCANS2-REQUEST"
   "<ASSEMBLESCANS2-RESPONSE>"
   "ASSEMBLESCANS2-RESPONSE"
  ))

